# Generated by Django 3.1.6 on 2021-03-31 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantapp', '0003_auto_20210330_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='body',
            new_name='Query',
        ),
    ]
