# Generated by Django 3.1.6 on 2021-03-31 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantapp', '0004_auto_20210331_0851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactUS',
        ),
    ]
